version: 0.0.0.{build}
image: Visual Studio 2022
install:
- ps: |
    $tagVersion = $($(git describe $(git rev-list --tags --max-count=1 origin/support/1.0)).TrimStart("v"))
    if ($env:appveyor_repo_tag -eq "true")
    {
       echo "Build triggered by a tag"
       $version = $tagVersion
    }
    else
    {
       $version = "$tagVersion.$env:appveyor_build_number"
    }
    echo $version
    Update-AppveyorBuild -Version $version
    & dotnet tool install -g dotnet-script

build_script:
- cmd: dotnet script build.csx -- package --version=%APPVEYOR_BUILD_VERSION%
test_script:
- cmd: dotnet script build.csx -- test
artifacts:
- path: '**/*.nupkg'
